name: Docker Image CI

on:
  push:
    branches: 
      - main
      - Sprint-4
  pull_request:
    branches: 
      - main
      - Sprint-4

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: chekcout code 
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker-compose up --build -d

    - name: remove docker networks, images and containers
      run: docker-compose down --rmi all
